version: '2'

services:
  ruby:
    build:
      context: .
    volumes:
    - ./bin:/app/bin
    - ./lib:/app/lib
    - ./spec:/app/spec
    - ./Gemfile:/app/Gemfile
    - ./Gemfile.lock:/app/Gemfile.lock
    - ./Rakefile:/app/Rakefile
    - ./asset_paths_from_manifest.gemspec:/app/asset_paths_from_manifest.gemspec
    - ./.rubocop.yml:/app/.rubocop.yml
    - bundle_install:/app/vendor/bundle
    - bundle:/app/.bundle
    tty: true
    stdin_open: true

volumes:
  bundle_install:
    driver: local
  bundle:
    driver: local
